steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'us.gcr.io/$PROJECT_ID/gateway:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/gateway:$COMMIT_SHA', './gateway-server']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/$PROJECT_ID/gateway:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - gateway
  - gateway=us.gcr.io/$PROJECT_ID/gateway:$COMMIT_SHA
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east4-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=primary'
